### ISSUE TITLE
L'erogatore dovrebbe essere INGV

### ISSUE THREAD

**Issue by ioggstream** [INGV/openapi#10]
## Mi aspetto che

l'erogatore qui sia INGV

https://github.com/INGV/openapi/blob/697c6fb8020b267b51ee9e7ca46f9f57dfad4cb2/src/fdsnws/event/0.0.1/openapi.yaml#L84

## Invece

è Valentino Lauciani @vlauciani

**Comment by vlauciani** [comment]
Si, corretto... anche se non e' molto intuitivo che sotto "contact" il "name" sia dell'erogatore ;-) 

Forse nello YAML avrei creato una struttura del tipo:
```
    contact:
      name: 'Valentino Lauciani'
      url: http://....
      email: valentino.lauciani@ingv.it
    provider:
      name: 'INGV'
      url: http://....
      email: it-team@ingv.it      
```

comunque ok, modifico la specifica.
