### ISSUE TITLE
`items` should be used with `array`

### ISSUE THREAD

**Issue by ioggstream** [INGV/openapi#7]
## I expect

`items` to be used with `arrays` here and elsewhere:

https://github.com/INGV/openapi/blob/111bdf7a5677bb2055523c8e68d880b9f719fb18/docs/definitions.yaml#L19

## instead

it's used with numbers too

## eg

```
# OK
type: number
format: int32
# OK
type: array
items:
  type: number
  format: int32

# KO
type: number
items:
  type: number
  format: int32
```
https://swagger.io/docs/specification/data-models/data-types/
